services:
- type: web
  name: 'Staging: Typesense'
  branch: staging
  env: docker
  repo: https://github.com/theclasscode/typesense.git
  plan: starter
  previewPlan: free
  healthCheckPath: /health
  disk:
    name: typesense-data
    mountPath: /typesense-data
    sizeGB: 1  
  envVars:
  - key: TYPESENSE_API_KEY
    generateValue: true
  - key: TYPESENSE_DATA_DIR
    value: /typesense-data
  - key: TYPESENSE_ENABLE_CORS
    value: true
